export { default as About } from './about'
export { default as Footer } from './footer'
export { default as Header } from './header'
export { default as Hero } from './hero'
export { default as Skills } from './skills'
export { default as Testimonials } from './testimonials'
export { default as Work } from './work'
